apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-app
    version: blue  # <-- switch to 'green' for green deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
